name: Setup Deployment Tools

on:
  push:
    branches:
      - none
  pull_request:
    branches: 
      - none
  workflow_call:

jobs:
    install_skaffold:
      runs-on: ubuntu-latest
      steps:
        - name: 'Install CD tool: skaffold'
          run: |
            curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
            sudo install skaffold /usr/local/bin/
    install_kustomize:
      runs-on: ubuntu-latest
      steps:
        - name: 'Install CD tool: kustomize'
          run: |
            curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
            sudo install skaffold /usr/local/bin/


